package codegen

import (
	"sort"

	"github.com/amine/figma-kit/internal/theme"
)

// Preamble generates the standard use_figma preamble: font loading + theme color constants.
func Preamble(b *Builder, t *theme.Theme) {
	b.Comment("Auto-generated by figma-kit")
	b.Linef("// Theme: %s", t.Name)
	b.Blank()

	b.FontLoading()

	b.Comment("--- Theme Colors ---")
	names := make([]string, 0, len(t.Colors))
	for name := range t.Colors {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		c := t.Colors[name]
		b.Linef("const %s={r:%s,g:%s,b:%s};", name, fmtFloat(c.R), fmtFloat(c.G), fmtFloat(c.B))
	}
	b.Blank()
}

// PreambleWithPage generates page setup + standard preamble.
func PreambleWithPage(b *Builder, t *theme.Theme, pageIndex int) {
	b.PageSetup(pageIndex)
	Preamble(b, t)
}
