package cli

import (
	"bytes"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	"github.com/dop-amine/figma-kit/internal/codegen"
	"github.com/dop-amine/figma-kit/internal/theme"
)

const maxComposeChars = 50000

type composeRecipe struct {
	Theme string   `yaml:"theme"`
	Page  int      `yaml:"page"`
	Steps []string `yaml:"steps"`
}

func newComposeCmd() *cobra.Command {
	var recipePath string
	cmd := &cobra.Command{
		Use:   `compose [flags] "cmd1 args..." "cmd2 args..." ...`,
		Short: "Batch N commands into a single JS payload for one use_figma call",
		Long: `Compose batches multiple figma-kit commands into a single JavaScript
payload. The shared preamble (page setup, fonts, theme colors, helpers) is
emitted once, and each command body is wrapped in { } for scope isolation.

Helpers are tree-shaken: only functions actually used by your steps are included
(typically ~3KB instead of 14KB). Each step's main node is pushed to _results[],
enabling cross-step references via --parent _results[0] or fx --last.

Use with 'exec' for direct Figma execution:
  figma-kit exec compose -t noir "ui section --title X" "card glass --parent _results[0]"

Or let an AI agent capture the output and send it to use_figma.`,
		Example: `  # Section + cards with cross-step references
  figma-kit compose -t noir \
    "ui section --title 'Features' --label 'FEATURES'" \
    "card glass --parent _results[0] --title 'Fast'" \
    "card glass --parent _results[0] --title 'Secure'"

  # Card with chained effects via --last
  figma-kit compose -t noir \
    "card glass --title Dashboard" \
    "fx noise --last" \
    "fx glow --last --position center"

  # From a recipe YAML
  figma-kit compose --recipe landing.yml

  # Direct execution
  figma-kit exec compose -t noir --recipe landing.yml`,
		Args: cobra.ArbitraryArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			steps, themeName, pageIdx, err := resolveComposeSteps(args, recipePath)
			if err != nil {
				return err
			}
			if len(steps) == 0 {
				return fmt.Errorf("no steps — provide command strings as args or use --recipe")
			}

			if themeName == "" {
				themeName = flagTheme
			}
			if themeName == "" {
				themeName = "default"
			}
			if pageIdx < 0 {
				pageIdx = resolvePage()
			}

			t, err := theme.Load(themeName)
			if err != nil {
				return fmt.Errorf("loading theme %q: %w", themeName, err)
			}

			js, err := composeSteps(t, pageIdx, steps)
			if err != nil {
				return err
			}

			if len(js) > maxComposeChars {
				fmt.Fprintf(os.Stderr, "Warning: composed output is %d chars (limit %d). Consider splitting.\n", len(js), maxComposeChars)
			}

			output(js)
			return nil
		},
	}
	cmd.Flags().StringVar(&recipePath, "recipe", "", "Path to a compose recipe YAML file")
	return cmd
}

func resolveComposeSteps(args []string, recipePath string) (steps []string, themeName string, page int, err error) {
	page = -1
	if recipePath != "" {
		data, readErr := os.ReadFile(recipePath)
		if readErr != nil {
			return nil, "", -1, fmt.Errorf("reading recipe: %w", readErr)
		}
		var rec composeRecipe
		if err := yaml.Unmarshal(data, &rec); err != nil {
			return nil, "", -1, fmt.Errorf("parsing recipe YAML: %w", err)
		}
		steps = rec.Steps
		themeName = rec.Theme
		if rec.Page > 0 {
			page = rec.Page
		}
	}
	steps = append(steps, args...)
	return steps, themeName, page, nil
}

type capturedStep struct {
	label  string
	fullJS string
	ids    string
	body   string
}

// composeSteps generates a single JS payload from N command steps.
func composeSteps(t *theme.Theme, pageIdx int, steps []string) (string, error) {
	var captured []capturedStep

	for i, step := range steps {
		step = strings.TrimSpace(step)
		if step == "" {
			continue
		}

		if err := validateComposableStep(step); err != nil {
			return "", fmt.Errorf("step %d: %w", i+1, err)
		}

		fullJS, err := captureStepFull(step)
		if err != nil {
			return "", fmt.Errorf("step %d (%q): %w", i+1, truncate(step, 60), err)
		}

		ids := extractReturnIDs(fullJS)
		body := stripPreambleAndReturn(fullJS)
		body = strings.TrimRight(body, "\n")

		captured = append(captured, capturedStep{
			label:  truncate(step, 80),
			fullJS: fullJS,
			ids:    ids,
			body:   body,
		})
	}

	// Determine which helpers are actually used across all step bodies.
	needed := detectNeededHelpers(captured)

	master := codegen.New()

	master.Comment("Auto-generated by figma-kit compose")
	master.Linef("// Theme: %s | Steps: %d", t.Name, len(captured))
	master.Blank()

	emitSupersetPreamble(master, t, pageIdx, needed)

	master.Line("const _ids = [];")
	master.Line("const _results = [];")
	master.Blank()

	for i, cs := range captured {
		master.Linef("// --- Step %d: %s ---", i+1, cs.label)
		master.Line("{")
		master.Raw(cs.body)
		if cs.ids != "" {
			master.Linef("  _ids.push(%s);", cs.ids)
			master.Linef("  _results.push(%s);", firstID(cs.ids))
		}
		master.Line("}")
		master.Blank()
	}

	master.Line("return { createdNodeIds: _ids };")
	return master.String(), nil
}

// firstID extracts the first ID expression from a comma-separated list.
func firstID(ids string) string {
	parts := strings.SplitN(ids, ",", 2)
	return strings.TrimSpace(parts[0])
}

// detectNeededHelpers scans all captured step bodies for references to helper
// functions and returns the deduplicated set of names needed, including
// transitive dependencies.
func detectNeededHelpers(steps []capturedStep) []string {
	available := codegen.AvailableHelpers()
	needed := make(map[string]bool)

	allBodies := strings.Builder{}
	for _, cs := range steps {
		allBodies.WriteString(cs.body)
		allBodies.WriteByte('\n')
	}
	combined := allBodies.String()

	for _, name := range available {
		if strings.Contains(combined, name+"(") {
			needed[name] = true
		}
	}

	// Resolve transitive deps: scan each needed helper's body for refs to others
	changed := true
	for changed {
		changed = false
		for _, name := range available {
			if needed[name] {
				continue
			}
			for dep := range needed {
				src := codegen.HelperFunc(dep)
				if strings.Contains(src, name+"(") {
					needed[name] = true
					changed = true
				}
			}
		}
	}

	result := make([]string, 0, len(needed))
	for _, name := range available {
		if needed[name] {
			result = append(result, name)
		}
	}
	return result
}

// emitSupersetPreamble emits the union of Standard + UI preambles plus only needed helpers.
func emitSupersetPreamble(b *codegen.Builder, t *theme.Theme, pageIdx int, neededHelpers []string) {
	b.Comment("--- Preamble (shared) ---")
	b.PageSetup(pageIdx)
	b.FontLoadingFromTheme(t.Fonts.Heading, t.Fonts.Body, t.Fonts.Mono, t.Fonts.Weights)

	names := make([]string, 0, len(t.Colors))
	for k := range t.Colors {
		names = append(names, k)
	}
	sort.Strings(names)
	b.Comment("Theme colors")
	for _, name := range names {
		c := t.Colors[name]
		b.Linef("const %s=%s;", name, codegen.FormatRGB(codegen.RGB{R: c.R, G: c.G, B: c.B}))
	}
	b.Blank()

	b.Comment("Type scale")
	emitTypeToken := func(key, suffix string, defSize int, defStyle string) {
		fs, st := defSize, defStyle
		if spec, ok := t.Type[key]; ok {
			fs = spec.FontSize
			if spec.Style != "" {
				st = spec.Style
			}
		}
		b.Linef("const TY_%s=%d; const ST_%s=%q;", suffix, fs, suffix, st)
	}
	emitTypeToken("body", "BODY", 16, "Regular")
	emitTypeToken("small", "SMALL", 13, "Regular")
	emitTypeToken("label", "LABEL", 11, "Medium")
	emitTypeToken("h4", "H4", 22, "Semi Bold")
	b.Blank()

	if len(neededHelpers) > 0 {
		b.Comment("Helpers (tree-shaken)")
		b.Raw(codegen.HelperFuncs(neededHelpers...))
		b.Blank()
	}
}

// validateComposableStep checks that a step targets a composable command.
func validateComposableStep(step string) error {
	args := splitShellArgs(step)
	if len(args) == 0 {
		return fmt.Errorf("empty step")
	}

	root := newRootCmd()
	target, _, err := root.Find(args)
	if err != nil || target == nil {
		return fmt.Errorf("unknown command: %s", strings.Join(args, " "))
	}

	if target.Annotations == nil || target.Annotations["composable"] != "true" {
		return fmt.Errorf("%q is not composable — it does not emit Plugin API JS. Use it separately", target.CommandPath())
	}
	return nil
}

// captureStepFull runs a figma-kit subcommand and captures its full JS output.
func captureStepFull(step string) (string, error) {
	args := splitShellArgs(step)

	root := newRootCmd()
	root.SetArgs(args)

	origStdout := os.Stdout
	r, w, err := os.Pipe()
	if err != nil {
		return "", err
	}
	os.Stdout = w

	execErr := root.Execute()

	_ = w.Close()
	os.Stdout = origStdout

	var captured bytes.Buffer
	_, _ = captured.ReadFrom(r)

	if execErr != nil {
		return "", fmt.Errorf("command failed: %w", execErr)
	}

	return captured.String(), nil
}

// stripPreambleAndReturn removes preamble lines, helper function definitions,
// and return statements from captured command output.
func stripPreambleAndReturn(js string) string {
	helperSrc := codegen.AllHelpers()
	js = strings.Replace(js, helperSrc, "", 1)

	lines := strings.Split(js, "\n")
	var result []string
	inFontsArray := false

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		if strings.HasPrefix(trimmed, "const fonts = [") {
			inFontsArray = true
			continue
		}
		if inFontsArray {
			if trimmed == "];" {
				inFontsArray = false
			}
			continue
		}

		if strings.HasPrefix(trimmed, "const pg = figma.root.children[") ||
			trimmed == "await figma.setCurrentPageAsync(pg);" ||
			trimmed == "for (const fn of fonts) await figma.loadFontAsync(fn);" ||
			strings.HasPrefix(trimmed, "// Auto-generated by figma-kit") ||
			strings.HasPrefix(trimmed, "// Theme:") ||
			strings.HasPrefix(trimmed, "// --- Theme Colors ---") ||
			strings.HasPrefix(trimmed, "// Theme colors") ||
			strings.HasPrefix(trimmed, "// Type scale") ||
			strings.HasPrefix(trimmed, "// --- Helpers ---") {
			continue
		}

		if themeConstRe.MatchString(trimmed) {
			continue
		}

		if strings.HasPrefix(trimmed, "const TY_") || strings.HasPrefix(trimmed, "const ST_") {
			continue
		}

		if strings.HasPrefix(trimmed, "return { createdNodeIds:") ||
			strings.HasPrefix(trimmed, "return 'Done'") {
			continue
		}

		result = append(result, line)
	}

	// Collapse runs of blank lines
	collapsed := collapseBlankLines(strings.Join(result, "\n"))
	return collapsed
}

func collapseBlankLines(s string) string {
	for strings.Contains(s, "\n\n\n") {
		s = strings.ReplaceAll(s, "\n\n\n", "\n\n")
	}
	return strings.TrimLeft(s, "\n")
}

var themeConstRe = regexp.MustCompile(`^const [A-Z][A-Z_]*=\{r:`)


var returnIDsRe = regexp.MustCompile(`return\s*\{\s*createdNodeIds:\s*\[([^\]]+)\]\s*\}`)
var returnExprRe = regexp.MustCompile(`return\s+['"]`)

// extractReturnIDs parses return expressions from the body to collect IDs.
// Returns the expression to push, or empty string if not found.
func extractReturnIDs(body string) string {
	if m := returnIDsRe.FindStringSubmatch(body); len(m) > 1 {
		return m[1]
	}
	return ""
}

// splitShellArgs splits a command string respecting quoted arguments.
func splitShellArgs(s string) []string {
	var args []string
	var current strings.Builder
	inSingle := false
	inDouble := false

	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '\'' && !inDouble:
			inSingle = !inSingle
		case c == '"' && !inSingle:
			inDouble = !inDouble
		case c == ' ' && !inSingle && !inDouble:
			if current.Len() > 0 {
				args = append(args, current.String())
				current.Reset()
			}
		default:
			current.WriteByte(c)
		}
	}
	if current.Len() > 0 {
		args = append(args, current.String())
	}
	return args
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-3] + "..."
}
