package cli

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/dop-amine/figma-kit/internal/codegen"
	"github.com/dop-amine/figma-kit/internal/theme"
)

func newThemeCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "theme",
		Short: "Theme management (init, preview)",
	}
	cmd.AddCommand(newThemeInitCmd())
	cmd.AddCommand(newThemePreviewCmd())
	return cmd
}

func newThemeInitCmd() *cobra.Command {
	var (
		name    string
		desc    string
		bgHex   string
		priHex  string
		accHex  string
		outPath string
	)

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Generate a new theme JSON from a few colors",
		Long: `Create a complete figma-kit theme from 3 hex colors.

Provide a background, primary, and accent color, and figma-kit will derive
the full palette (card, text, muted, stroke, warn, error, success), plus
sensible defaults for typography, effects, and spacing.

If no flags are given, prints a starter template to stdout.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if bgHex == "" && priHex == "" && accHex == "" {
				return printStarterTemplate()
			}

			if bgHex == "" {
				bgHex = "#0D0F17"
			}
			if priHex == "" {
				priHex = "#3366FF"
			}
			if accHex == "" {
				accHex = "#14B8A6"
			}
			if name == "" {
				name = "My Theme"
			}
			if desc == "" {
				desc = "Custom theme generated by figma-kit"
			}

			bg, err := theme.HexToRGB(bgHex)
			if err != nil {
				return err
			}
			primary, err := theme.HexToRGB(priHex)
			if err != nil {
				return err
			}
			accent, err := theme.HexToRGB(accHex)
			if err != nil {
				return err
			}

			jsonStr, err := theme.GenerateThemeJSON(name, desc, bg, primary, accent)
			if err != nil {
				return err
			}

			if outPath != "" {
				dir := filepath.Dir(outPath)
				if err := os.MkdirAll(dir, 0o755); err != nil {
					return fmt.Errorf("creating directory: %w", err)
				}
				if err := os.WriteFile(outPath, []byte(jsonStr+"\n"), 0o644); err != nil {
					return fmt.Errorf("writing file: %w", err)
				}
				_, _ = fmt.Fprintf(os.Stderr, "Theme written to %s\n", outPath)
				return nil
			}

			fmt.Println(jsonStr)
			return nil
		},
	}

	cmd.Flags().StringVar(&name, "name", "", "Theme name")
	cmd.Flags().StringVar(&desc, "desc", "", "Theme description")
	cmd.Flags().StringVar(&bgHex, "bg", "", "Background hex color (e.g. #0D0F17)")
	cmd.Flags().StringVar(&priHex, "primary", "", "Primary accent hex color (e.g. #3366FF)")
	cmd.Flags().StringVar(&accHex, "accent", "", "Secondary accent hex color (e.g. #14B8A6)")
	cmd.Flags().StringVarP(&outPath, "output", "o", "", "Output file path (default: stdout)")

	return cmd
}

func printStarterTemplate() error {
	tmpl := `{
  "name": "My Theme",
  "description": "Describe your theme aesthetic in one sentence.",

  "colors": {
    "BG":      { "r": 0.05, "g": 0.06, "b": 0.09 },
    "CARD":    { "r": 0.09, "g": 0.10, "b": 0.15 },
    "WT":      { "r": 0.96, "g": 0.97, "b": 0.98 },
    "BD":      { "r": 0.78, "g": 0.81, "b": 0.85 },
    "MT":      { "r": 0.45, "g": 0.48, "b": 0.55 },
    "BL":      { "r": 0.20, "g": 0.40, "b": 1.00 },
    "TL":      { "r": 0.08, "g": 0.72, "b": 0.65 },
    "STK":     { "r": 0.14, "g": 0.16, "b": 0.22 },
    "WARN":    { "r": 1.00, "g": 0.60, "b": 0.20 },
    "ERR":     { "r": 1.00, "g": 0.35, "b": 0.35 },
    "SUCCESS": { "r": 0.20, "g": 0.80, "b": 0.50 }
  }
}
`
	fmt.Print(tmpl)
	return nil
}

func newThemePreviewCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "preview",
		Short: "Generate a Figma preview page for a theme",
		Long: `Outputs use_figma JS that creates a compact theme preview in Figma:
color swatches, type scale specimens, and sample components.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			t, err := resolveTheme(cmd)
			if err != nil {
				return err
			}
			page := resolvePage()

			b := codegen.New()
			codegen.PreambleWithPage(b, t, page)

			b.Comment("Theme Preview: " + t.Name)
			b.Line("const root = figma.createFrame();")
			b.Linef("root.name = 'Theme Preview: %s';", t.Name)
			b.Line("root.resize(1200, 800);")
			b.Line("root.fills = [{type:'SOLID', color:BG}];")
			b.Line("root.layoutMode = 'VERTICAL';")
			b.Line("root.paddingTop = 60; root.paddingBottom = 60;")
			b.Line("root.paddingLeft = 60; root.paddingRight = 60;")
			b.Line("root.itemSpacing = 40;")
			b.Line("root.primaryAxisSizingMode = 'AUTO';")
			b.Line("figma.currentPage.appendChild(root);")
			b.Blank()

			b.Comment("Title")
			b.Line("{ const t = figma.createText();")
			b.Line("  await figma.loadFontAsync({family:'Inter', style:'Bold'});")
			b.Line("  t.fontName = {family:'Inter', style:'Bold'};")
			b.Linef("  t.characters = 'Theme: %s';", t.Name)
			b.Line("  t.fontSize = 36; t.fills = [{type:'SOLID', color:WT}];")
			b.Line("  root.appendChild(t); }")
			b.Blank()

			b.Comment("Color swatches row")
			b.Line("const swatchRow = figma.createFrame();")
			b.Line("swatchRow.name = 'Color Swatches';")
			b.Line("swatchRow.layoutMode = 'HORIZONTAL';")
			b.Line("swatchRow.itemSpacing = 12;")
			b.Line("swatchRow.fills = [];")
			b.Line("swatchRow.counterAxisSizingMode = 'AUTO';")
			b.Line("swatchRow.primaryAxisSizingMode = 'AUTO';")
			b.Line("root.appendChild(swatchRow);")

			for _, name := range t.ColorNames() {
				b.Linef("{ const f = figma.createFrame(); f.name = %q; f.resize(80,80);", name)
				b.Linef("  f.fills = [{type:'SOLID', color:%s}];", name)
				b.Line("  f.cornerRadius = 12;")
				b.Line("  const lb = figma.createText();")
				b.Line("  await figma.loadFontAsync({family:'Geist Mono', style:'Medium'});")
				b.Line("  lb.fontName = {family:'Geist Mono', style:'Medium'};")
				b.Linef("  lb.characters = %q; lb.fontSize = 9;", name)
				b.Line("  lb.fills = [{type:'SOLID', color:WT}];")
				b.Line("  lb.x = 8; lb.y = 60; f.appendChild(lb);")
				b.Line("  swatchRow.appendChild(f); }")
			}
			b.Blank()

			b.Comment("Type scale specimens")
			typeEntries := []struct{ key, label string }{
				{"h1", "h1 — Heading One"},
				{"h2", "h2 — Heading Two"},
				{"h3", "h3 — Heading Three"},
				{"body", "body — Body text"},
				{"small", "small — Small text"},
			}
			for _, entry := range typeEntries {
				ts, ok := t.Type[entry.key]
				if !ok {
					continue
				}
				family := "Inter"
				if ts.Family != "" {
					family = ts.Family
				}
				b.Linef("{ const t = figma.createText();")
				b.Linef("  await figma.loadFontAsync({family:%q, style:%q});", family, ts.Style)
				b.Linef("  t.fontName = {family:%q, style:%q};", family, ts.Style)
				b.Linef("  t.characters = %q;", entry.label)
				b.Linef("  t.fontSize = %d;", ts.FontSize)
				b.Line("  t.fills = [{type:'SOLID', color:WT}];")
				b.Line("  root.appendChild(t); }")
			}
			b.Blank()

			b.Comment("Sample button")
			b.Line("{ const btn = figma.createFrame(); btn.name = 'Sample Button';")
			b.Line("  btn.resize(160, 44); btn.cornerRadius = 10;")
			b.Line("  btn.fills = [{type:'SOLID', color:BL}];")
			b.Line("  btn.layoutMode = 'HORIZONTAL'; btn.primaryAxisAlignItems = 'CENTER';")
			b.Line("  btn.counterAxisAlignItems = 'CENTER'; btn.paddingLeft = 24; btn.paddingRight = 24;")
			b.Line("  const lb = figma.createText();")
			b.Line("  await figma.loadFontAsync({family:'Inter', style:'Semi Bold'});")
			b.Line("  lb.fontName = {family:'Inter', style:'Semi Bold'};")
			b.Line("  lb.characters = 'Get Started'; lb.fontSize = 15;")
			b.Line("  lb.fills = [{type:'SOLID', color:WT}];")
			b.Line("  btn.appendChild(lb); root.appendChild(btn); }")

			b.ReturnIDs("root.id")
			output(b.String())
			return nil
		},
	}
}
