#!/usr/bin/env node

import { Command } from 'commander';
import { readFileSync, readdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import chalk from 'chalk';

const __dirname = dirname(fileURLToPath(import.meta.url));
const LIB_DIR = resolve(__dirname, '../../lib');

function loadTheme(name) {
  const path = resolve(LIB_DIR, 'themes', `${name}.json`);
  try {
    return JSON.parse(readFileSync(path, 'utf-8'));
  } catch {
    console.error(chalk.red(`Theme "${name}" not found at ${path}`));
    process.exit(1);
  }
}

function loadHelpers() {
  return readFileSync(resolve(LIB_DIR, 'helpers.js'), 'utf-8');
}

function loadTemplate(name) {
  const path = resolve(LIB_DIR, 'templates', `${name}.js`);
  try {
    return readFileSync(path, 'utf-8');
  } catch {
    console.error(chalk.red(`Template "${name}" not found at ${path}`));
    process.exit(1);
  }
}

function generatePreamble(themeName) {
  const theme = loadTheme(themeName);
  const colors = theme.colors;

  const lines = [
    '// Auto-generated by figma-kit CLI',
    `// Theme: ${theme.name}`,
    '',
    '// --- Font Loading ---',
    'const fonts = [',
    "  {family:'Inter',style:'Bold'},{family:'Inter',style:'Semi Bold'},",
    "  {family:'Inter',style:'Medium'},{family:'Inter',style:'Regular'},",
    "  {family:'Inter',style:'Light'},",
    "  {family:'Geist Mono',style:'Regular'},{family:'Geist Mono',style:'Medium'}",
    '];',
    'for (const fn of fonts) await figma.loadFontAsync(fn);',
    '',
    '// --- Theme Colors ---',
  ];

  for (const [key, val] of Object.entries(colors)) {
    lines.push(`const ${key}={r:${val.r},g:${val.g},b:${val.b}};`);
  }

  return lines.join('\n');
}

const program = new Command();

program
  .name('figma-kit')
  .description('CLI for programmatic Figma design using the Design Kit')
  .version('0.1.0');

program
  .command('preamble')
  .description('Generate the use_figma preamble (theme colors + font loading)')
  .option('-t, --theme <name>', 'Theme name', 'default')
  .action((opts) => {
    console.log(generatePreamble(opts.theme));
  });

program
  .command('helpers')
  .description('Output the full helpers.js code for injection into use_figma')
  .action(() => {
    console.log(loadHelpers());
  });

program
  .command('template <name>')
  .description('Output a template (slide, one-pager-print, storyboard-panel)')
  .action((name) => {
    console.log(loadTemplate(name));
  });

program
  .command('themes')
  .description('List available themes')
  .action(() => {
    const files = readdirSync(resolve(LIB_DIR, 'themes'))
      .filter(f => f.endsWith('.json'));
    console.log(chalk.bold('\nAvailable themes:\n'));
    for (const f of files) {
      const theme = JSON.parse(readFileSync(resolve(LIB_DIR, 'themes', f), 'utf-8'));
      const name = f.replace('.json', '');
      console.log(`  ${chalk.cyan(name.padEnd(12))} ${theme.description || theme.name}`);
    }
    console.log('');
  });

program
  .command('scaffold')
  .description('Generate a full use_figma code block ready for execution')
  .option('-t, --theme <name>', 'Theme name', 'default')
  .option('--template <name>', 'Template to include')
  .option('-p, --page <index>', 'Page index (0-based)', '0')
  .action((opts) => {
    const preamble = generatePreamble(opts.theme);
    const helpers = loadHelpers();

    const lines = [
      `const pg = figma.root.children[${opts.page}];`,
      'await figma.setCurrentPageAsync(pg);',
      '',
      preamble,
      '',
      '// --- Helpers ---',
      helpers,
    ];

    if (opts.template) {
      const tmpl = loadTemplate(opts.template);
      lines.push('', '// --- Template ---', tmpl);
    }

    lines.push('', "return 'Done';");
    console.log(lines.join('\n'));
  });

program
  .command('info')
  .description('Show the Design Kit directory structure')
  .action(() => {
    console.log(chalk.bold('\nFigma Design Kit Structure:\n'));
    console.log(`  ${chalk.cyan('SKILL.md')}              Cursor Skill (AI workflow instructions)`);
    console.log(`  ${chalk.cyan('lib/')}`);
    console.log(`    ${chalk.cyan('helpers.js')}          Core helper functions`);
    console.log(`    ${chalk.cyan('themes/')}`);
    console.log(`      ${chalk.dim('default.json')}      Dark theme`);
    console.log(`      ${chalk.dim('light.json')}        Light theme`);
    console.log(`      ${chalk.dim('arkham.json')}       Arkham brand theme`);
    console.log(`    ${chalk.cyan('templates/')}`);
    console.log(`      ${chalk.dim('slide.js')}          LinkedIn carousel slide`);
    console.log(`      ${chalk.dim('one-pager-print.js')} B2B sales one-pager`);
    console.log(`      ${chalk.dim('storyboard-panel.js')} Styleframe + panoramic`);
    console.log(`  ${chalk.cyan('references/')}`);
    console.log(`    ${chalk.dim('figma-plugin-api.md')} API gotchas`);
    console.log(`    ${chalk.dim('glassmorphism.md')}    Glass card recipes`);
    console.log(`    ${chalk.dim('naming-conventions.md')} Frame naming rules`);
    console.log(`  ${chalk.cyan('cli/')}`);
    console.log(`    ${chalk.dim('src/index.js')}       This CLI tool`);
    console.log('');
  });

program.parse();
